"""Templates for Mind files."""

MEMORY_TEMPLATE = """<!-- MIND MEMORY - Append as you work. Write naturally.
Keywords: decided, problem, learned, tried, fixed, blocked, todo -->

# {project_name}

## Project State
- Goal:
- Stack: {stack}
- Blocked: None

## Gotchas
<!-- Project-specific gotchas -->

---

## Session Log

## {date}

(Start writing here)

---
"""

CONTEXT_TEMPLATE = """# IMPORTANT: Write memories as you work

As you work on this project, append to `.mind/MEMORY.md` whenever you:
- Make a decision → `decided X because Y`
- Hit a problem → `problem: X`
- Learn something → `learned that X`
- Fix something → `fixed X by doing Y`

Do this throughout the conversation, not just at the end.

---

<!-- MIND:CONTEXT - Auto-generated by Mind. Do not edit. -->
## Stack
{stack}

## Gotchas
(None yet - add to .mind/MEMORY.md Gotchas section)
<!-- MIND:END -->"""

GITIGNORE_CONTENT = """.index/
"""
