"""Templates for Mind files (v2: daemon-free, MCP-driven)."""

SESSION_TEMPLATE = """# Session: {date}

## Experience
<!-- Raw moments, thoughts, what's happening -->

## Blockers

## Rejected
<!-- What didn't work and why -->

## Assumptions
<!-- What I'm assuming true -->

"""

MEMORY_TEMPLATE = """<!-- MIND MEMORY - Append as you work. Write naturally.
Keywords: decided, problem, learned, tried, fixed, blocked, KEY, important
Wikilinks: Use [[MEMORY#L123]] to link to specific lines (Obsidian-compatible)
Sync: To sync across devices, add .mind/ folder to your Obsidian vault -->

# {project_name}

## Project State
- Goal:
- Stack: {stack}
- Blocked: None

## Gotchas
<!-- Project-specific gotchas -->

---

## Session Log

## {date}

(Start writing here)

<!-- End session with: ## DATE | summary of what happened | mood: X -->
---
"""

CONTEXT_TEMPLATE = """## Memory (Mind)

This project uses Mind for persistent memory across sessions.

### Required Protocol

1. **Session Start**: ALWAYS call `mind_recall()` before responding to the first message. This loads context from previous sessions.

2. **During Work**: Use `mind_log(message, type)` to capture what happens:
   - `mind_log("chose X over Y - simpler", type="decision")` -> MEMORY.md
   - `mind_log("API returns 500 on large payloads", type="problem")` -> MEMORY.md
   - `mind_log("Safari needs vendor prefix for X", type="learning")` -> MEMORY.md
   - `mind_log("resolved by increasing timeout", type="progress")` -> MEMORY.md
   - `mind_log("working on auth flow", type="experience")` -> SESSION.md
   - `mind_log("build keeps failing", type="blocker")` -> SESSION.md
   - `mind_log("tried Redis - too complex", type="rejected")` -> SESSION.md
   - `mind_log("assuming user has stable internet", type="assumption")` -> SESSION.md

3. **Session End**: Summarize with `## DATE | what happened | mood: X`

### Two-Layer Memory

**MEMORY.md** (permanent, cross-session):
- Decisions, learnings, problems, progress
- Use types: `decision`, `learning`, `problem`, `progress`

**SESSION.md** (ephemeral, within-session):
- Raw experience, blockers, rejected approaches, assumptions
- Use types: `experience`, `blocker`, `rejected`, `assumption`
- Valuable items get promoted to MEMORY.md on session gap (>30 min)

### Tools Available

- `mind_recall()` - Load session context (CALL FIRST!)
- `mind_log(msg, type)` - Log to session or memory (routes by type)
- `mind_session()` - Get current session state
- `mind_blocker(description)` - Log blocker + auto-search memory for solutions
- `mind_search(query)` - Find specific memories
- `mind_remind(msg, when)` - Set time or context reminder
- `mind_checkpoint()` - Force process pending memories
- `mind_edges(intent)` - Check for gotchas before coding
- `mind_status()` - Check memory health
- `mind_spawn_helper(problem)` - Package problem for fresh agent investigation

---

<!-- MIND:CONTEXT - Auto-generated by Mind. Do not edit. -->
## Stack
{stack}

## Gotchas
(None yet - add to .mind/MEMORY.md Gotchas section)
<!-- MIND:END -->"""

GITIGNORE_CONTENT = """# Mind files are personal/local - don't commit
*
!.gitignore
"""

SELF_IMPROVE_TEMPLATE = """<!-- MIND SELF-IMPROVEMENT - Cross-project patterns about YOU
This file lives in ~/.mind/ and persists across all projects.
It helps Claude remember your patterns, preferences, and blind spots. -->

# Self-Improvement Patterns

## Preferences
<!-- How you like to work: coding style, workflow, communication -->
<!-- Format: PREFERENCE: [category] description -->

## Skills
<!-- What you're good at in specific contexts -->
<!-- Format: SKILL: [stack:context] description -->

## Blind Spots
<!-- Things you consistently miss or forget -->
<!-- Format: BLIND_SPOT: [category] description -->

## Anti-Patterns
<!-- Approaches that don't work for you -->
<!-- Format: ANTI_PATTERN: [category] description -->

## Learning Styles
<!-- How you learn best - extracted from feedback patterns -->
<!-- Format: LEARNING_STYLE: [context] description -->

---

## Feedback Log
<!-- Raw corrections for pattern extraction (3+ occurrences = pattern) -->
<!-- Format: FEEDBACK: [date] context -> correction -->

"""
